@HostAddress = http://localhost:5219/api/v1/Constants
@id = replace-your-id
@size = 25
@page = 1
@ascending = True
@property = ID
@search = 

GET {{HostAddress}}/{{size}}/{{page}}/{{ascending}}/{{property}}/{{search}}
Accept: application/json

###
GET {{HostAddress}}/{{id}}
Accept: application/json

###
POST {{HostAddress}}
Content-type: application/json

{
	"order": 0,
	"group": "",
	"key": "",
	"value": ""
}

###
PUT {{HostAddress}}/{{id}}
Content-type: application/json

{
	"order": 0,
	"group": "",
	"key": "",
	"value": ""
}

###
DELETE {{HostAddress}}/{{id}}
